### ISSUE TITLE
What kind of feature is suitable for this scenery? (deal with synonym)

### ISSUE THREAD

**Issue by guotong1988** [YuriyGuts/kaggle-quora-question-pairs#2]
Train data: `Who is Michael Jordan? ` and `Who is Air Jordan? ` are one right match.
The test data is `Who is Jumpman Jordan? ` and `Who is Air Jordan? `

What feature should I add for training? Can the model capture the match info for this case?

Thank you！！！
@YuriyGuts

**Comment by YuriyGuts** [comment]
I haven't researched this topic in depth but my best bet would be relying on the word vectors trained on a corpus that contains those synonyms in similar contexts. E.g. Wikipedia containing articles about the basketball player and the brand of clothing named after him.
