### ISSUE TITLE
I am confused whether the 1st solution used XGB / LGBM as their main model?

### ISSUE THREAD

**Issue by guotong1988** [YuriyGuts/kaggle-quora-question-pairs#5]
https://www.kaggle.com/c/quora-question-pairs/discussion/34355
What is the function of XGB / LGBM in this 1st solution?
Thank you very much.
@YuriyGuts

**Comment by YuriyGuts** [comment]
You should really ask the authors about this rather than me. They used a 4-level model stack with XGB and LGBM on the first layer and mentioned this in their solution description which you linked above. Beyond that, I cannot possibly know because they did not publish the entire code.

**Comment by guotong1988** [comment]
Thank you very much.
